import type { DiscoveryTrack } from "./streaming";

export const EXTRA_DISCOVERY_CATALOG: DiscoveryTrack[] = [
  { artist: "Interpol", title: "Obstacle 1", genre: "Rock", why: "taut post-punk revival tension", source: "curated" },
  { artist: "Yeah Yeah Yeahs", title: "Maps", genre: "Rock", why: "raw guitar ache with a huge hook", source: "curated" },
  { artist: "The National", title: "Bloodbuzz Ohio", genre: "Rock", why: "baritone dread and slow-burn drums", source: "curated" },
  { artist: "Arctic Monkeys", title: "Do I Wanna Know?", genre: "Rock", why: "heavy nocturnal guitar swing", source: "curated" },
  { artist: "TV on the Radio", title: "Wolf Like Me", genre: "Rock", why: "art-rock urgency and jagged lift", source: "curated" },
  { artist: "Parquet Courts", title: "Wide Awake", genre: "Rock", why: "nervy punk-funk motion", source: "curated" },
  { artist: "Squid", title: "Narrator", genre: "Rock", why: "restless post-punk escalation", source: "curated" },
  { artist: "Shame", title: "One Rizla", genre: "Rock", why: "loose British punk bite", source: "curated" },
  { artist: "Black Country, New Road", title: "Concorde", genre: "Rock", why: "orchestral indie-rock sprawl", source: "curated" },
  { artist: "Dry Cleaning", title: "Scratchcard Lanyard", genre: "Rock", why: "deadpan spoken post-punk", source: "curated" },
  { artist: "Slowdive", title: "When the Sun Hits", genre: "Rock", why: "shoegaze bloom and melancholy", source: "curated" },
  { artist: "My Bloody Valentine", title: "When You Sleep", genre: "Rock", why: "blurred guitar-pop euphoria", source: "curated" },
  { artist: "Smashing Pumpkins", title: "1979", genre: "Rock", why: "dreamy alt-rock nostalgia", source: "curated" },
  { artist: "Pixies", title: "Where Is My Mind?", genre: "Rock", why: "surreal loud-quiet guitar landmark", source: "curated" },
  { artist: "Pavement", title: "Gold Soundz", genre: "Rock", why: "slacker indie-rock warmth", source: "curated" },

  { artist: "Fred again..", title: "Marea (We've Lost Dancing)", genre: "Electronic", why: "communal dance-floor emotion", source: "curated" },
  { artist: "Romy", title: "Strong", genre: "Electronic", why: "clean club-pop catharsis", source: "curated" },
  { artist: "Disclosure", title: "Latch", genre: "Electronic", why: "mainstream UK house lift", source: "curated" },
  { artist: "Justice", title: "D.A.N.C.E.", genre: "Electronic", why: "bright French electro-pop", source: "curated" },
  { artist: "M83", title: "Kim and Jessie", genre: "Electronic", why: "neon synth nostalgia", source: "curated" },
  { artist: "The Avalanches", title: "Since I Left You", genre: "Electronic", why: "sample-collage sunshine", source: "curated" },
  { artist: "Kiasmos", title: "Looped", genre: "Electronic", why: "piano-led minimal techno", source: "curated" },
  { artist: "Ben Bohmer", title: "Beyond Beliefs", genre: "Electronic", why: "melodic deep-house glide", source: "curated" },
  { artist: "Lane 8", title: "Atlas", genre: "Electronic", why: "patient melodic house build", source: "curated" },
  { artist: "Bonobo", title: "Cirrus", genre: "Electronic", why: "organic downtempo pulse", source: "curated" },
  { artist: "Tycho", title: "Awake", genre: "Electronic", why: "sunlit synth instrumental", source: "curated" },
  { artist: "Against All Logic", title: "This Old House Is All I Have", genre: "Electronic", why: "dusty house pressure", source: "curated" },
  { artist: "Skee Mask", title: "Rev8617", genre: "Electronic", why: "breakbeat techno drift", source: "curated" },
  { artist: "Lone", title: "Airglow Fires", genre: "Electronic", why: "rave nostalgia and soft chords", source: "curated" },
  { artist: "Burial", title: "Raver", genre: "Electronic", why: "ghostly post-club ambience", source: "curated" },

  { artist: "Frank Ocean", title: "Nights", genre: "Pop", why: "left-field R&B pivot and mood shift", source: "curated" },
  { artist: "SZA", title: "Good Days", genre: "Pop", why: "hazy R&B-pop reflection", source: "curated" },
  { artist: "Solange", title: "Cranes in the Sky", genre: "Pop", why: "minimal soul-pop elegance", source: "curated" },
  { artist: "Faye Webster", title: "Kingston", genre: "Pop", why: "laid-back indie-pop ache", source: "curated" },
  { artist: "Clairo", title: "Bags", genre: "Pop", why: "soft indie-pop intimacy", source: "curated" },
  { artist: "Men I Trust", title: "Show Me How", genre: "Pop", why: "silky dream-pop groove", source: "curated" },
  { artist: "The 1975", title: "Somebody Else", genre: "Pop", why: "glossy sad-pop pulse", source: "curated" },
  { artist: "Robyn", title: "Dancing On My Own", genre: "Pop", why: "lonely dance-pop release", source: "curated" },
  { artist: "Carly Rae Jepsen", title: "Run Away With Me", genre: "Pop", why: "maximal pop euphoria", source: "curated" },
  { artist: "Sky Ferreira", title: "Everything Is Embarrassing", genre: "Pop", why: "cool synth-pop melancholy", source: "curated" },
  { artist: "Hatchie", title: "Sure", genre: "Pop", why: "shoegaze-pop brightness", source: "curated" },
  { artist: "Rina Sawayama", title: "XS", genre: "Pop", why: "metallic pop maximalism", source: "curated" },
  { artist: "Jessie Ware", title: "Spotlight", genre: "Pop", why: "luxury disco-pop glide", source: "curated" },
  { artist: "Christine and the Queens", title: "Tilted", genre: "Pop", why: "art-pop rhythm and poise", source: "curated" },
  { artist: "Blood Orange", title: "You're Not Good Enough", genre: "Pop", why: "sleek funk-pop introspection", source: "curated" },

  { artist: "Elliott Smith", title: "Angeles", genre: "Folk", why: "fingerpicked melancholy and close vocals", source: "curated" },
  { artist: "Iron & Wine", title: "Naked As We Came", genre: "Folk", why: "hushed acoustic intimacy", source: "curated" },
  { artist: "Bright Eyes", title: "First Day of My Life", genre: "Folk", why: "plainspoken indie-folk warmth", source: "curated" },
  { artist: "Wilco", title: "Jesus, Etc.", genre: "Folk", why: "alt-country strings and soft regret", source: "curated" },
  { artist: "The War on Drugs", title: "Red Eyes", genre: "Folk", why: "heartland synth-rock lift", source: "curated" },
  { artist: "Angel Olsen", title: "Shut Up Kiss Me", genre: "Folk", why: "rough-edged folk-rock hook", source: "curated" },
  { artist: "Courtney Barnett", title: "Avant Gardener", genre: "Folk", why: "talky indie-rock storytelling", source: "curated" },
  { artist: "Sharon Van Etten", title: "Seventeen", genre: "Folk", why: "grown-up indie-rock catharsis", source: "curated" },
  { artist: "The Tallest Man on Earth", title: "The Gardener", genre: "Folk", why: "ragged acoustic urgency", source: "curated" },
  { artist: "Laura Marling", title: "Song for Our Daughter", genre: "Folk", why: "literate modern folk poise", source: "curated" },
  { artist: "Jason Isbell", title: "Cover Me Up", genre: "Folk", why: "country-folk confession", source: "curated" },
  { artist: "Sturgill Simpson", title: "Turtles All the Way Down", genre: "Folk", why: "cosmic country songwriting", source: "curated" },
  { artist: "Kacey Musgraves", title: "Slow Burn", genre: "Folk", why: "country-pop patience and glow", source: "curated" },
  { artist: "Mitski", title: "Francis Forever", genre: "Folk", why: "compact indie ache", source: "curated" },
  { artist: "Florist", title: "Red Bird Pt. 2", genre: "Folk", why: "fragile room-close folk", source: "curated" },

  { artist: "Miles Davis", title: "Blue in Green", genre: "Instrumental", why: "cool jazz stillness", source: "curated" },
  { artist: "John Coltrane", title: "Naima", genre: "Instrumental", why: "spiritual jazz tenderness", source: "curated" },
  { artist: "Alice Coltrane", title: "Journey in Satchidananda", genre: "Instrumental", why: "modal harp-jazz meditation", source: "curated" },
  { artist: "Kamasi Washington", title: "Truth", genre: "Instrumental", why: "modern spiritual-jazz sprawl", source: "curated" },
  { artist: "BADBADNOTGOOD", title: "Time Moves Slow", genre: "Instrumental", why: "jazz-soul haze", source: "curated" },
  { artist: "GoGo Penguin", title: "Hopopono", genre: "Instrumental", why: "piano-trio minimal momentum", source: "curated" },
  { artist: "Mogwai", title: "Auto Rock", genre: "Instrumental", why: "patient post-rock swell", source: "curated" },
  { artist: "This Will Destroy You", title: "The Mighty Rio Grande", genre: "Instrumental", why: "cinematic guitar crescendo", source: "curated" },
  { artist: "Hammock", title: "Turn Away and Return", genre: "Instrumental", why: "ambient post-rock shimmer", source: "curated" },
  { artist: "Laraaji", title: "I Am Sky", genre: "Instrumental", why: "zither ambient glow", source: "curated" },
  { artist: "Kaitlyn Aurelia Smith", title: "An Intention", genre: "Instrumental", why: "modular synth organicism", source: "curated" },
  { artist: "Hiroshi Yoshimura", title: "Green", genre: "Instrumental", why: "Japanese ambient clarity", source: "curated" },
  { artist: "Penguin Cafe Orchestra", title: "Perpetuum Mobile", genre: "Instrumental", why: "chamber minimal charm", source: "curated" },
  { artist: "Olafur Arnalds", title: "Near Light", genre: "Instrumental", why: "piano and strings lift", source: "curated" },
  { artist: "Dustin O'Halloran", title: "We Move Lightly", genre: "Instrumental", why: "plainspoken piano motion", source: "curated" },

  { artist: "Nas", title: "N.Y. State of Mind", genre: "Hip-Hop", why: "canonical street-level boom-bap", source: "curated" },
  { artist: "Wu-Tang Clan", title: "C.R.E.A.M.", genre: "Hip-Hop", why: "grimy classic rap gravity", source: "curated" },
  { artist: "Mobb Deep", title: "Shook Ones, Pt. II", genre: "Hip-Hop", why: "cold piano-loop menace", source: "curated" },
  { artist: "Clipse", title: "Grindin'", genre: "Hip-Hop", why: "minimal percussion and steel", source: "curated" },
  { artist: "Pusha T", title: "Numbers on the Boards", genre: "Hip-Hop", why: "sparse, snarling rap pressure", source: "curated" },
  { artist: "Vince Staples", title: "Norf Norf", genre: "Hip-Hop", why: "deadpan west-coast minimalism", source: "curated" },
  { artist: "Earl Sweatshirt", title: "Chum", genre: "Hip-Hop", why: "foggy introspective rap", source: "curated" },
  { artist: "Noname", title: "Diddy Bop", genre: "Hip-Hop", why: "light-footed jazz rap", source: "curated" },
  { artist: "Saba", title: "Photosynthesis", genre: "Hip-Hop", why: "Chicago rap warmth", source: "curated" },
  { artist: "Denzel Curry", title: "Walkin", genre: "Hip-Hop", why: "urgent rap momentum", source: "curated" },
  { artist: "JID", title: "151 Rum", genre: "Hip-Hop", why: "kinetic flow and tension", source: "curated" },
  { artist: "Freddie Gibbs", title: "Crime Pays", genre: "Hip-Hop", why: "smooth coke-rap pocket", source: "curated" },
  { artist: "Madvillain", title: "Accordion", genre: "Hip-Hop", why: "minimal abstract rap classic", source: "curated" },
  { artist: "The Pharcyde", title: "Passin' Me By", genre: "Hip-Hop", why: "wistful jazz-rap hook", source: "curated" },
  { artist: "Digable Planets", title: "Rebirth of Slick", genre: "Hip-Hop", why: "cool jazz-rap swing", source: "curated" },

  { artist: "Burna Boy", title: "Ye", genre: "International", why: "global afro-fusion hook", source: "curated" },
  { artist: "Wizkid", title: "Ojuelegba", genre: "International", why: "melodic afrobeats glide", source: "curated" },
  { artist: "Rema", title: "Calm Down", genre: "International", why: "recognizable afropop bounce", source: "curated" },
  { artist: "Koffee", title: "Toast", genre: "International", why: "bright dancehall ease", source: "curated" },
  { artist: "Bob Marley & The Wailers", title: "Could You Be Loved", genre: "International", why: "familiar reggae uplift", source: "curated" },
  { artist: "Manu Chao", title: "Me Gustas Tu", genre: "International", why: "global pop singalong", source: "curated" },
  { artist: "Jorge Ben Jor", title: "Taj Mahal", genre: "International", why: "Brazilian groove and chant", source: "curated" },
  { artist: "Gilberto Gil", title: "Toda Menina Baiana", genre: "International", why: "sunny MPB rhythm", source: "curated" },
  { artist: "Caetano Veloso", title: "Tropicalia", genre: "International", why: "psychedelic Brazilian pop", source: "curated" },
  { artist: "Seu Jorge", title: "Carolina", genre: "International", why: "warm samba-funk swing", source: "curated" },
  { artist: "Arooj Aftab", title: "Mohabbat", genre: "International", why: "ghazal-jazz atmosphere", source: "curated" },
  { artist: "Anoushka Shankar", title: "Boat to Nowhere", genre: "International", why: "modern sitar fusion", source: "curated" },
  { artist: "Lila Downs", title: "Zapata Se Queda", genre: "International", why: "folk roots with dramatic force", source: "curated" },
  { artist: "C. Tangana", title: "Tu Me Dejaste De Querer", genre: "International", why: "Spanish pop-flamenco crossover", source: "curated" },
  { artist: "Natalia Lafourcade", title: "Hasta la Raiz", genre: "International", why: "Mexican folk-pop tenderness", source: "curated" },

  { artist: "Radiohead", title: "Idioteque", genre: "Experimental", why: "apocalyptic electronic rock", source: "curated" },
  { artist: "Bjork", title: "Joga", genre: "Experimental", why: "orchestral electronic eruption", source: "curated" },
  { artist: "Kate Bush", title: "Running Up That Hill", genre: "Experimental", why: "art-pop with familiar emotional scale", source: "curated" },
  { artist: "David Bowie", title: "Blackstar", genre: "Experimental", why: "late-career art-rock unease", source: "curated" },
  { artist: "Talk Talk", title: "I Believe in You", genre: "Experimental", why: "post-rock spiritual quiet", source: "curated" },
  { artist: "Scott Walker", title: "Farmer in the City", genre: "Experimental", why: "orchestral avant-pop dread", source: "curated" },
  { artist: "The Microphones", title: "I Want Wind to Blow", genre: "Experimental", why: "lo-fi folk abstraction", source: "curated" },
  { artist: "Mount Eerie", title: "Real Death", genre: "Experimental", why: "unvarnished grief minimalism", source: "curated" },
  { artist: "Low", title: "Days Like These", genre: "Experimental", why: "distorted slowcore transcendence", source: "curated" },
  { artist: "Jockstrap", title: "Concrete Over Water", genre: "Experimental", why: "fractured art-pop structure", source: "curated" },
  { artist: "100 gecs", title: "hand crushed by a mallet", genre: "Experimental", why: "hyperpop chaos and compression", source: "curated" },
  { artist: "Death Grips", title: "I've Seen Footage", genre: "Experimental", why: "industrial rap velocity", source: "curated" },
  { artist: "Flying Lotus", title: "Do the Astral Plane", genre: "Experimental", why: "jazz-electronic beat mutation", source: "curated" },
  { artist: "Thundercat", title: "Them Changes", genre: "Experimental", why: "virtuosic funk-pop oddity", source: "curated" },
  { artist: "King Gizzard & The Lizard Wizard", title: "Robot Stop", genre: "Experimental", why: "psych-rock machine momentum", source: "curated" },
];

export const EXTRA_FAMILIAR_LANDMARKS: DiscoveryTrack[] = [
  { artist: "The Beatles", title: "Come Together", genre: "Rock", why: "familiar rock groove landmark", source: "curated", familiarity: "mainstream" },
  { artist: "Led Zeppelin", title: "Kashmir", genre: "Rock", why: "classic heavy-rock scale", source: "curated", familiarity: "mainstream" },
  { artist: "Queen", title: "Bohemian Rhapsody", genre: "Rock", why: "canonical theatrical rock anchor", source: "curated", familiarity: "mainstream" },
  { artist: "Prince", title: "When Doves Cry", genre: "Pop", why: "familiar art-pop and funk landmark", source: "curated", familiarity: "mainstream" },
  { artist: "Michael Jackson", title: "Billie Jean", genre: "Pop", why: "global pop groove reference", source: "curated", familiarity: "mainstream" },
  { artist: "Beyonce", title: "Crazy in Love", genre: "Pop", why: "recognizable pop-R&B ignition", source: "curated", familiarity: "mainstream" },
  { artist: "Kanye West", title: "Runaway", genre: "Hip-Hop", why: "mainstream rap-art-pop bridge", source: "curated", familiarity: "mainstream" },
  { artist: "Drake", title: "Passionfruit", genre: "Hip-Hop", why: "familiar airy rap-pop anchor", source: "curated", familiarity: "mainstream" },
  { artist: "Massive Attack", title: "Teardrop", genre: "Electronic", why: "widely known trip-hop landmark", source: "curated", familiarity: "mainstream" },
  { artist: "The Prodigy", title: "Breathe", genre: "Electronic", why: "recognizable big-beat aggression", source: "curated", familiarity: "mainstream" },
  { artist: "Enya", title: "Only Time", genre: "Instrumental", why: "familiar ambient-adjacent reference", source: "curated", familiarity: "mainstream" },
  { artist: "Explosions in the Sky", title: "First Breath After Coma", genre: "Instrumental", why: "recognizable post-rock entry point", source: "curated", familiarity: "mainstream" },
  { artist: "Simon & Garfunkel", title: "The Sound of Silence", genre: "Folk", why: "canonical folk anchor", source: "curated", familiarity: "mainstream" },
  { artist: "Bob Dylan", title: "Don't Think Twice, It's All Right", genre: "Folk", why: "classic songwriting reference", source: "curated", familiarity: "mainstream" },
  { artist: "Toto", title: "Africa", genre: "International", why: "global-pop familiarity point", source: "curated", familiarity: "mainstream" },
  { artist: "Shakira", title: "Hips Don't Lie", genre: "International", why: "recognizable Latin-pop crossover", source: "curated", familiarity: "mainstream" },
  { artist: "Talking Heads", title: "Once in a Lifetime", genre: "Experimental", why: "familiar art-rock gateway", source: "curated", familiarity: "mainstream" },
  { artist: "Gnarls Barkley", title: "Crazy", genre: "Experimental", why: "left-field pop hit anchor", source: "curated", familiarity: "mainstream" },
];
